### ISSUE TITLE
How to deploy a hexo blog to Github? - research

### ISSUE THREAD

**Issue by ela-b** [ela-b/elablog#2]

**Comment by ela-b** [comment]
@suricaten I'd like you to show me how to do it, but if you find some good tutorial, you could also leave the link in the comments. The basic hexo tutorial didn't work for me as I was getting some errors I couldn't solve with Stackoverflow etc.

**Comment by suricaten** [comment]
I´ve deployed the test blog with no issues, just following Hexo tutorial.
Maybe its an obvious question but, have you tried to repeat all the process step by step?
If you could also show me what errors did u have, maybe we can see where is the problem.
