### ISSUE TITLE
ela-b.github.io/blog

### ISSUE THREAD

**Issue by ela-b** [ela-b/elablog#5]
Currently, the blog is available at https://ela-b.github.io/public/index.html. How to replace that link with ela-b.github.io/blog ?

**Comment by suricaten** [comment]
Rename the public folder as blog

**Comment by ela-b** [comment]
Could you do it for me please, and ensure it works?




Ela Bednarek

Phone: +48 601 891 982 <+48%20601%20891%20982>
elzbieta.bednarek@gmail.com <ela.bednarek@asyncode.com> |  skype:
ela_asyncode
Find me on LinkedIn <http://cn.linkedin.com/in/elzbietabednarek/> & twitter
<https://twitter.com/elamustrun>

**Comment by suricaten** [comment]
I´ll do it, but first i need access to the repo.
This is an old one

**Comment by ela-b** [comment]
Done :)




Ela Bednarek

Phone: +48 601 891 982 <+48%20601%20891%20982>
elzbieta.bednarek@gmail.com <ela.bednarek@asyncode.com> |  skype:
ela_asyncode
Find me on LinkedIn <http://cn.linkedin.com/in/elzbietabednarek/> & twitter
<https://twitter.com/elamustrun>

**Comment by ela-b** [comment]
Please make sure the other links also work. Any questions - let me know.
Thanks!




Ela Bednarek

Phone: +48 601 891 982 <+48%20601%20891%20982>
elzbieta.bednarek@gmail.com <ela.bednarek@asyncode.com> |  skype:
ela_asyncode
Find me on LinkedIn <http://cn.linkedin.com/in/elzbietabednarek/> & twitter
<https://twitter.com/elamustrun>

**Comment by suricaten** [comment]
Done and working. You should try it anyways, just to be sure.

**Comment by ela-b** [comment]
All works, thanks!




Ela Bednarek

Phone: +48 601 891 982 <+48%20601%20891%20982>
elzbieta.bednarek@gmail.com <ela.bednarek@asyncode.com> |  skype:
ela_asyncode
Find me on LinkedIn <http://cn.linkedin.com/in/elzbietabednarek/> & twitter
<https://twitter.com/elamustrun>
